### ISSUE TITLE
I can't build LakeOS

### ISSUE THREAD

**Issue by unsafecast** [vincenthouyi/LakeOS#1]
I just cloned the repo, `cd`-ed into `kernel`, and did `make`. Here's the output:

![Capture](https://user-images.githubusercontent.com/76212078/117422979-de6a6780-af28-11eb-9b56-5b0df2194ced.PNG)

I'm running Ubuntu 20.04 (WSL2). Let me know if you need more info :)

**Comment by unsafecast** [comment]
Oh I just realized I have the wrong binutils, sorry

**Comment by unsafecast** [comment]
Okay so I now have the correct toolchain but the error it still there. Did I do something wrong?

**Comment by vincenthouyi** [comment]
Seems make couldn't find dependent files under ../lib. Probably the Makefile is not compatible with the make you are using. I will fix this asap

**Comment by vincenthouyi** [comment]
can you try the latest commit? I removed the lines in Makefile. Sorry I haven't test compiling the project on a Linux for a while.

**Comment by unsafecast** [comment]
@vincenthouyi nice! it works now, thank you!

Also don't be sorry :)
