### ISSUE TITLE
LakeOS-atags seems to be private

### ISSUE THREAD

**Issue by unsafecast** [vincenthouyi/LakeOS#2]
Hello again. The makefile now works, but it tries to pull in https://github.com/vincenthouyi/LakeOS-atags, which seems to be private.

**Comment by vincenthouyi** [comment]
@unsafecast, I put the lib in the project source tree. You can try the latest commit. I tested on a Ubuntu 20.04 with rustc version `rustc 1.54.0-nightly (676ee1472 2021-05-06)`.

**Comment by unsafecast** [comment]
It worked, thanks!
